### ISSUE TITLE
[Error] asciinema needs a UTF-8

### ISSUE THREAD

**Issue by abhisekp** [asciinema/asciinema#160]
I'm getting this error in Ubuntu 16.04 64b after adding the ppa and updating. Previously, I had `Version: 1.0.16` and now I've `Version: 1.2.0-1`.
Previously, it was all working fine. Why does this error show? What are the benefits this check? https://github.com/asciinema/asciinema/blob/master/main.go#L103

```sh
➔ asciinema --version    
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.

➔ locale
LANG=en_IN
LANGUAGE=en_IN:en
LC_CTYPE=en_IN
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=
```

**Comment by sickill** [comment]
We have this requirement in order to force all commands that you run inside asciinema recording session to use UTF-8. By ensuring the captured stdout stream is in UTF-8, the asciinema web player implementation can be much simpler, without need to deal with char encodings and all related complexity.

What's the character encoding you're using? (I don't see encoding specification in your locale output).

**Comment by abhisekp** [comment]
@sickill I didn't manually change anything. It was like that when I installed my Ubuntu box. I live in India, btw.

`en_IN` probably stands for Indian English :confused:

**Comment by abhisekp** [comment]
@sickill something for you https://bugs.launchpad.net/ubuntu/+source/python-defaults/+bug/653259

**Comment by abhisekp** [comment]
@sickill this is my output of `/usr/share/i18n/SUPPORTED`
`en_IN` is actually `UTF-8` :smiley_cat:  

```text
en_HK.UTF-8 UTF-8
en_HK ISO-8859-1
en_IE.UTF-8 UTF-8
en_IE ISO-8859-1
en_IE@euro ISO-8859-15
en_IN UTF-8 <----------------------------------------- 
en_NG UTF-8
en_NZ.UTF-8 UTF-8
en_NZ ISO-8859-1
en_PH.UTF-8 UTF-8
en_PH ISO-8859-1
```

**Comment by sickill** [comment]
Not sure what would be the best way to fix this. But meanwhile you can alias `asciinema="LC_CTYPE=en_IN.UTF-8 asciinema"` maybe?

**Comment by abhisekp** [comment]
That is so wrong. LOL. 
But whatever it takes to run the app :wink: 
If I had to climb a mountain :mount_fuji: , I would do that. :smile:

**Comment by abhisekp** [comment]
@sickill Thank you. It works but please fix this soon. :construction_worker: :hammer: :construction:

**Comment by sickill** [comment]
I know it's not the prettiest solution, but as a temporary workaround must do for now ;)

**Comment by sickill** [comment]
@abhisekp I just released v1.3.0 which should solve this problem. Can you check it? `sudo pip3 install asciinema`.

**Comment by abhisekp** [comment]
@sickill yay! it works ...

**Comment by ReSearchITEng** [comment]
This is still failing, even on asciinema 1.4 .
```bash
$asciinema
asciinema needs a UTF-8 native locale to run. Check the output of `locale` command.```
$locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C```

**SOLUTION:**
```export LC_ALL=${LANG}```

**Comment by sickill** [comment]
It's enough to only set `LC_CTYPE=*.UTF-8`.

**Comment by ReSearchITEng** [comment]
I see.
So the defaults we have in RHEL/Centos are not good enough for asciinema?
```
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

**Comment by sickill** [comment]
Looks like they're not enough indeed :)

**Comment by just4t** [comment]
Same issue having by default:

```
# locale
LANG=en_US
LANGUAGE=
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
```
 Worked here by entering:

`export LC_ALL=en_US.UTF-8`

Then,  the final output to `locale` command: 

```
# locale
LANG=en_US
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by just4t** [comment]
Noticed still fails on some CLOUD server(s) running _Ubuntu 16.04 LTS_ (not detected the issue over _Ubuntu 18.04 LTS_ CLOUD servers) ...

Fixed through SSH with:
`update-locale LANG=en_US.UTF-8`

Or manually by editing the _/etc/default/locale_ file with this content:
`LANG="en_US.UTF-8"`

Hope this helps others!
